
repositories {
  maven {
    name = "EMI"
    url = "https://maven.terraformersmc.com/"
  }
}


dependencies {
  // TODO: once botania is ported, we can re enable here
  // compileOnly "vazkii.botania:Botania:[VERSION]:api"

  //when testing with local unreleased library
  //implementation "local.mods:flib:${minecraft_version}-${flib_version}"

  //deps outside of tmpl
  implementation "curse.maven:jeed-532286:${jeed_file}"

  localRuntime "vazkii.patchouli:Patchouli:${minecraft_version}-${patchouli_version}-NEOFORGE"
// EMI for testing
//  compileOnly "dev.emi:emi-neoforge:${emi_version}:api"
//  runtimeOnly "dev.emi:emi-neoforge:${emi_version}"
}