
flib_version=0.2.7
flib_file=8309035

mod_id=cyclic
curse_id=239286
mod_version=1.14.1
mod_name=Cyclic
mod_group_id=com.lothrazar.cyclic
mod_license=SeeGithub
mod_authors=Lothrazar
mod_description=cyclic
modrinth_id=cyclic
curse_slug=cyclic


emi_version=1.1.23+1.21.1
jeed_file=7346553
