package com.lothrazar.cyclic.registry;

import com.lothrazar.cyclic.ModCyclic;
import com.lothrazar.cyclic.block.anvil.ContainerAnvil;
import com.lothrazar.cyclic.block.anvilmagma.ContainerAnvilMagma;
import com.lothrazar.cyclic.block.anvilvoid.ContainerAnvilVoid;
import com.lothrazar.cyclic.block.battery.ContainerBattery;
import com.lothrazar.cyclic.block.batteryclay.ContainerClayBattery;
import com.lothrazar.cyclic.block.beaconpotion.ContainerPotion;
import com.lothrazar.cyclic.block.breaker.ContainerBreaker;
import com.lothrazar.cyclic.block.cable.fluid.ContainerCableFluid;
import com.lothrazar.cyclic.block.cable.item.ContainerCableItem;
import com.lothrazar.cyclic.block.clock.ContainerClock;
import com.lothrazar.cyclic.block.collectfluid.ContainerFluidCollect;
import com.lothrazar.cyclic.block.collectitem.ContainerItemCollector;
import com.lothrazar.cyclic.block.crafter.ContainerCrafter;
import com.lothrazar.cyclic.block.crate.ContainerCrate;
import com.lothrazar.cyclic.block.cratemini.ContainerCrateMini;
import com.lothrazar.cyclic.block.crusher.ContainerCrusher;
import com.lothrazar.cyclic.block.detectorentity.ContainerDetector;
import com.lothrazar.cyclic.block.detectoritem.ContainerDetectorItem;
import com.lothrazar.cyclic.block.disenchant.ContainerDisenchant;
import com.lothrazar.cyclic.block.dropper.ContainerDropper;
import com.lothrazar.cyclic.block.expcollect.ContainerExpPylon;
import com.lothrazar.cyclic.block.fan.ContainerFan;
import com.lothrazar.cyclic.block.fishing.ContainerFisher;
import com.lothrazar.cyclic.block.forester.ContainerForester;
import com.lothrazar.cyclic.block.generatorfluid.ContainerGeneratorFluid;
import com.lothrazar.cyclic.block.generatorfood.ContainerGeneratorFood;
import com.lothrazar.cyclic.block.generatorfuel.ContainerGeneratorFuel;
import com.lothrazar.cyclic.block.generatoritem.ContainerGeneratorDrops;
import com.lothrazar.cyclic.block.generatorsolar.ContainerGeneratorSolar;
import com.lothrazar.cyclic.block.harvester.ContainerHarvester;
import com.lothrazar.cyclic.block.hopperfluid.ContainerFluidHopper;
import com.lothrazar.cyclic.block.hoppergold.ContainerGoldHopper;
import com.lothrazar.cyclic.block.laser.ContainerLaser;
import com.lothrazar.cyclic.block.magnet.ContainerMagnet;
import com.lothrazar.cyclic.block.melter.ContainerMelter;
import com.lothrazar.cyclic.block.miner.ContainerMiner;
import com.lothrazar.cyclic.block.packager.ContainerPackager;
import com.lothrazar.cyclic.block.peatfarm.ContainerPeatFarm;
import com.lothrazar.cyclic.block.placer.ContainerPlacer;
import com.lothrazar.cyclic.block.placerfluid.ContainerPlacerFluid;
import com.lothrazar.cyclic.block.screen.ContainerScreentext;
import com.lothrazar.cyclic.block.shapebuilder.ContainerStructure;
import com.lothrazar.cyclic.block.shapedata.ContainerShapedata;
import com.lothrazar.cyclic.block.solidifier.ContainerSolidifier;
import com.lothrazar.cyclic.block.soundplay.ContainerSoundPlayer;
import com.lothrazar.cyclic.block.soundrecord.ContainerSoundRecorder;
import com.lothrazar.cyclic.block.tp.ContainerTeleport;
import com.lothrazar.cyclic.block.uncrafter.ContainerUncraft;
import com.lothrazar.cyclic.block.user.ContainerUser;
import com.lothrazar.cyclic.block.wireless.energy.ContainerWirelessEnergy;
import com.lothrazar.cyclic.block.wireless.fluid.ContainerWirelessFluid;
import com.lothrazar.cyclic.block.wireless.item.ContainerWirelessItem;
import com.lothrazar.cyclic.block.wireless.redstone.ContainerTransmit;
import com.lothrazar.cyclic.block.workbench.ContainerWorkbench;
import com.lothrazar.cyclic.item.compass.ContainerGpsCompass;
import com.lothrazar.cyclic.item.crafting.CraftingBagContainer;
import com.lothrazar.cyclic.item.crafting.simple.CraftingStickContainer;
import com.lothrazar.cyclic.item.datacard.filter.ContainerFilterCard;
import com.lothrazar.cyclic.item.datacard.fluid.ContainerFluidFilterCard;
import com.lothrazar.cyclic.item.enderbook.EnderBookContainer;
import com.lothrazar.cyclic.item.lunchbox.ContainerLunchbox;
import com.lothrazar.cyclic.item.storagebag.ContainerStorageBag;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.world.inventory.MenuType;
import net.neoforged.neoforge.common.extensions.IMenuTypeExtension;
import net.neoforged.neoforge.registries.DeferredRegister;

import java.util.function.Supplier;


public class MenuTypeRegistry {

  public static final DeferredRegister<MenuType<?>> CONTAINERS = DeferredRegister.create(BuiltInRegistries.MENU, ModCyclic.MODID);

  public static final Supplier<MenuType<ContainerItemCollector>> COLLECTOR = CONTAINERS.register("collector", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerItemCollector(windowId, inv.player.level(), data.readBlockPos(), inv, inv.player)));
  public static final Supplier<MenuType<ContainerPeatFarm>> PEAT_FARM = CONTAINERS.register("peat_farm", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerPeatFarm(windowId, inv.player.level(), data.readBlockPos(), inv, inv.player)));
  public static final Supplier<MenuType<ContainerBattery>> BATTERY = CONTAINERS.register("battery", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerBattery(windowId, inv.player.level(), data.readBlockPos(), inv, inv.player)));
  public static final Supplier<MenuType<ContainerClayBattery>> BATTERY_CLAY = CONTAINERS.register("battery_clay", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerClayBattery(windowId, inv.player.level(), data.readBlockPos(), inv, inv.player)));
  public static final Supplier<MenuType<ContainerHarvester>> HARVESTER = CONTAINERS.register("harvester", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerHarvester(windowId, inv.player.level(), data.readBlockPos(), inv, inv.player)));
  public static final Supplier<MenuType<ContainerAnvil>> ANVIL = CONTAINERS.register("anvil", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerAnvil(windowId, inv.player.level(), data.readBlockPos(), inv, inv.player)));
  public static final Supplier<MenuType<ContainerPlacer>> PLACER = CONTAINERS.register("placer", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerPlacer(windowId, inv.player.level(), data.readBlockPos(), inv, inv.player)));
  public static final Supplier<MenuType<ContainerStructure>> STRUCTURE = CONTAINERS.register("structure", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerStructure(windowId, inv.player.level(), data.readBlockPos(), inv, inv.player)));
  public static final Supplier<MenuType<ContainerMelter>> MELTER = CONTAINERS.register("melter", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerMelter(windowId, inv.player.level(), data.readBlockPos(), inv, inv.player)));
  public static final Supplier<MenuType<ContainerSolidifier>> SOLIDIFIER = CONTAINERS.register("solidifier", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerSolidifier(windowId, inv.player.level(), data.readBlockPos(), inv, inv.player)));
  public static final Supplier<MenuType<ContainerBreaker>> BREAKER = CONTAINERS.register("breaker", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerBreaker(windowId, inv.player.level(), data.readBlockPos(), inv, inv.player)));
  public static final Supplier<MenuType<ContainerExpPylon>> EXPERIENCE_PYLON = CONTAINERS.register("experience_pylon", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerExpPylon(windowId, inv.player.level(), data.readBlockPos(), inv, inv.player)));
  public static final Supplier<MenuType<ContainerUser>> USER = CONTAINERS.register("user", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerUser(windowId, inv.player.level(), data.readBlockPos(), inv, inv.player)));
  public static final Supplier<MenuType<ContainerDetector>> DETECTOR_ENTITY = CONTAINERS.register("detector_entity", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerDetector(windowId, inv.player.level(), data.readBlockPos(), inv, inv.player)));
  public static final Supplier<MenuType<ContainerDetectorItem>> DETECTOR_ITEM = CONTAINERS.register("detector_item", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerDetectorItem(windowId, inv.player.level(), data.readBlockPos(), inv, inv.player)));
  public static final Supplier<MenuType<ContainerDisenchant>> DISENCHANTER = CONTAINERS.register("disenchanter", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerDisenchant(windowId, inv.player.level(), data.readBlockPos(), inv, inv.player)));
  public static final Supplier<MenuType<ContainerTransmit>> WIRELESS_TRANSMITTER = CONTAINERS.register("wireless_transmitter", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerTransmit(windowId, inv.player.level(), data.readBlockPos(), inv, inv.player)));
  public static final Supplier<MenuType<ContainerClock>> CLOCK = CONTAINERS.register("clock", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerClock(windowId, inv.player.level(), data.readBlockPos(), inv, inv.player)));
  public static final Supplier<MenuType<ContainerCrate>> CRATE = CONTAINERS.register("crate", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerCrate(windowId, inv.player.level(), data.readBlockPos(), inv, inv.player)));
  public static final Supplier<MenuType<ContainerCrateMini>> CRATE_MINI = CONTAINERS.register("crate_mini", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerCrateMini(windowId, inv.player.level(), data.readBlockPos(), inv, inv.player)));
  public static final Supplier<MenuType<ContainerPlacerFluid>> PLACER_FLUID = CONTAINERS.register("placer_fluid", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerPlacerFluid(windowId, inv.player.level(), data.readBlockPos(), inv, inv.player)));
  public static final Supplier<MenuType<ContainerFluidCollect>> COLLECTOR_FLUID = CONTAINERS.register("collector_fluid", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerFluidCollect(windowId, inv.player.level(), data.readBlockPos(), inv, inv.player)));
  public static final Supplier<MenuType<ContainerFan>> FAN = CONTAINERS.register("fan", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerFan(windowId, inv.player.level(), data.readBlockPos(), inv, inv.player)));
  public static final Supplier<MenuType<ContainerPotion>> BEACON = CONTAINERS.register("beacon", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerPotion(windowId, inv.player.level(), data.readBlockPos(), inv, inv.player)));
  public static final Supplier<MenuType<ContainerDropper>> DROPPER = CONTAINERS.register("dropper", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerDropper(windowId, inv.player.level(), data.readBlockPos(), inv, inv.player)));
  public static final Supplier<MenuType<ContainerForester>> FORESTER = CONTAINERS.register("forester", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerForester(windowId, inv.player.level(), data.readBlockPos(), inv, inv.player)));
  public static final Supplier<MenuType<ContainerMiner>> MINER = CONTAINERS.register("miner", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerMiner(windowId, inv.player.level(), data.readBlockPos(), inv, inv.player)));
  public static final Supplier<MenuType<ContainerScreentext>> SCREEN = CONTAINERS.register("screen", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerScreentext(windowId, inv.player.level(), data.readBlockPos(), inv, inv.player)));
  public static final Supplier<MenuType<ContainerAnvilMagma>> ANVIL_MAGMA = CONTAINERS.register("anvil_magma", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerAnvilMagma(windowId, inv.player.level(), data.readBlockPos(), inv, inv.player)));
  public static final Supplier<MenuType<ContainerUncraft>> UNCRAFTER = CONTAINERS.register("uncrafter", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerUncraft(windowId, inv.player.level(), data.readBlockPos(), inv, inv.player)));
  public static final Supplier<MenuType<ContainerCrafter>> CRAFTER = CONTAINERS.register("crafter", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerCrafter(windowId, inv.player.level(), data.readBlockPos(), inv, inv.player)));
  public static final Supplier<MenuType<ContainerShapedata>> COMPUTER_SHAPE = CONTAINERS.register("computer_shape", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerShapedata(windowId, inv.player.level(), data.readBlockPos(), inv, inv.player)));
  public static final Supplier<MenuType<ContainerWorkbench>> WORKBENCH = CONTAINERS.register("workbench", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerWorkbench(windowId, inv.player.level(), data.readBlockPos(), inv, inv.player)));
  public static final Supplier<MenuType<ContainerFisher>> FISHER = CONTAINERS.register("fisher", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerFisher(windowId, inv.player.level(), data.readBlockPos(), inv, inv.player)));
  public static final Supplier<MenuType<ContainerLaser>> LASER = CONTAINERS.register("laser", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerLaser(windowId, inv.player.level(), data.readBlockPos(), inv, inv.player)));
  public static final Supplier<MenuType<ContainerCableItem>> ITEM_PIPE = CONTAINERS.register("item_pipe", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerCableItem(windowId, inv.player.level(), data.readBlockPos(), inv, inv.player)));
  public static final Supplier<MenuType<ContainerCableFluid>> FLUID_PIPE = CONTAINERS.register("fluid_pipe", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerCableFluid(windowId, inv.player.level(), data.readBlockPos(), inv, inv.player)));
  public static final Supplier<MenuType<ContainerAnvilVoid>> ANVIL_VOID = CONTAINERS.register("anvil_void", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerAnvilVoid(windowId, inv.player.level(), data.readBlockPos(), inv, inv.player)));
  public static final Supplier<MenuType<ContainerWirelessEnergy>> WIRELESS_ENERGY = CONTAINERS.register("wireless_energy", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerWirelessEnergy(windowId, inv.player.level(), data.readBlockPos(), inv, inv.player)));
  public static final Supplier<MenuType<ContainerWirelessItem>> WIRELESS_ITEM = CONTAINERS.register("wireless_item", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerWirelessItem(windowId, inv.player.level(), data.readBlockPos(), inv, inv.player)));
  public static final Supplier<MenuType<ContainerWirelessFluid>> WIRELESS_FLUID = CONTAINERS.register("wireless_fluid", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerWirelessFluid(windowId, inv.player.level(), data.readBlockPos(), inv, inv.player)));
  public static final Supplier<MenuType<ContainerGeneratorFuel>> GENERATOR_FUEL = CONTAINERS.register("generator_fuel", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerGeneratorFuel(windowId, inv.player.level(), data.readBlockPos(), inv, inv.player)));
  public static final Supplier<MenuType<ContainerGeneratorFood>> GENERATOR_FOOD = CONTAINERS.register("generator_food", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerGeneratorFood(windowId, inv.player.level(), data.readBlockPos(), inv, inv.player)));
  public static final Supplier<MenuType<ContainerGeneratorDrops>> GENERATOR_DROPS = CONTAINERS.register("generator_item", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerGeneratorDrops(windowId, inv.player.level(), data.readBlockPos(), inv, inv.player)));
  public static final Supplier<MenuType<ContainerGeneratorFluid>> GENERATOR_FLUID = CONTAINERS.register("generator_fluid", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerGeneratorFluid(windowId, inv.player.level(), data.readBlockPos(), inv, inv.player)));
  public static final Supplier<MenuType<ContainerGeneratorSolar>> GENERATOR_SOLAR = CONTAINERS.register("generator_solar", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerGeneratorSolar(windowId, inv.player.level(), data.readBlockPos(), inv, inv.player)));
  public static final Supplier<MenuType<ContainerPackager>> PACKAGER = CONTAINERS.register("packager", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerPackager(windowId, inv.player.level(), data.readBlockPos(), inv, inv.player)));
  public static final Supplier<MenuType<ContainerSoundRecorder>> SOUND_RECORDER = CONTAINERS.register("sound_recorder", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerSoundRecorder(windowId, inv.player.level(), data.readBlockPos(), inv, inv.player)));
  public static final Supplier<MenuType<ContainerSoundPlayer>> SOUND_PLAYER = CONTAINERS.register("sound_player", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerSoundPlayer(windowId, inv.player.level(), data.readBlockPos(), inv, inv.player)));
  public static final Supplier<MenuType<ContainerCrusher>> CRUSHER = CONTAINERS.register("crusher", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerCrusher(windowId, inv.player.level(), data.readBlockPos(), inv, inv.player)));
  public static final Supplier<MenuType<ContainerTeleport>> TELEPORT = CONTAINERS.register("teleport", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerTeleport(windowId, inv.player.level(), data.readBlockPos(), inv, inv.player)));
  public static final Supplier<MenuType<ContainerMagnet>> MAGNET = CONTAINERS.register("magnet", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerMagnet(windowId, inv.player.level(), data.readBlockPos(), inv, inv.player)));
  public static final Supplier<MenuType<ContainerGoldHopper>> HOPPER_GOLD = CONTAINERS.register("hopper_gold", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerGoldHopper(windowId, inv.player.level(), data.readBlockPos(), inv, inv.player)));
  public static final Supplier<MenuType<ContainerFluidHopper>> HOPPER_FLUID = CONTAINERS.register("hopper_fluid", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerFluidHopper(windowId, inv.player.level(), data.readBlockPos(), inv, inv.player)));
  //  Items with containers
  public static final Supplier<MenuType<EnderBookContainer>> ENDER_BOOK = CONTAINERS.register("ender_book", () -> IMenuTypeExtension.create((windowId, inv, data) -> new EnderBookContainer(windowId, inv, inv.player)));
  public static final Supplier<MenuType<ContainerStorageBag>> STORAGE_BAG = CONTAINERS.register("storage_bag", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerStorageBag(windowId, inv, inv.player, data.readInt())));
  public static final Supplier<MenuType<CraftingBagContainer>> CRAFTING_BAG = CONTAINERS.register("crafting_bag", () -> IMenuTypeExtension.create((windowId, inv, data) -> new CraftingBagContainer(windowId, inv, inv.player, data.readInt())));
  public static final Supplier<MenuType<CraftingStickContainer>> CRAFTING_STICK = CONTAINERS.register("crafting_stick", () -> IMenuTypeExtension.create((windowId, inv, data) -> new CraftingStickContainer(windowId, inv, inv.player, data.readInt())));
  public static final Supplier<MenuType<ContainerFilterCard>> FILTER_DATA = CONTAINERS.register("filter_data", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerFilterCard(windowId, inv, inv.player)));
  public static final Supplier<MenuType<ContainerFluidFilterCard>> FLUID_DATA = CONTAINERS.register("fluid_data", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerFluidFilterCard(windowId, inv, inv.player)));
  public static final Supplier<MenuType<ContainerLunchbox>> LUNCHBOX = CONTAINERS.register("lunchbox", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerLunchbox(windowId, inv, inv.player)));
  public static final Supplier<MenuType<ContainerGpsCompass>> GPS_COMPASS = CONTAINERS.register("compass_gps", () -> IMenuTypeExtension.create((windowId, inv, data) -> new ContainerGpsCompass(windowId, inv, inv.player)));
}
