package com.lothrazar.cyclic.registry;

import com.lothrazar.cyclic.ModCyclic;
// import com.lothrazar.cyclic.block.antipotion.TileAntiBeacon;
import com.lothrazar.cyclic.block.antipotion.TileAntiBeacon;
import com.lothrazar.cyclic.block.anvil.TileAnvilAuto;
import com.lothrazar.cyclic.block.anvilmagma.TileAnvilMagma;
import com.lothrazar.cyclic.block.anvilvoid.TileAnvilVoid;
import com.lothrazar.cyclic.block.battery.TileBattery;
import com.lothrazar.cyclic.block.batteryclay.TileClayBattery;
import com.lothrazar.cyclic.block.batterycreative.TileBatteryInfinite;
import com.lothrazar.cyclic.block.beaconpotion.TilePotionBeacon;
import com.lothrazar.cyclic.block.beaconredstone.TileBeaconRedstone;
import com.lothrazar.cyclic.block.bedrock.UnbreakablePoweredTile;
import com.lothrazar.cyclic.block.breaker.TileBreaker;
import com.lothrazar.cyclic.block.cable.bundled.TileCableBundled;
import com.lothrazar.cyclic.block.cable.energy.TileCableEnergy;
import com.lothrazar.cyclic.block.cable.fluid.TileCableFluid;
import com.lothrazar.cyclic.block.cable.item.TileCableItem;
import com.lothrazar.cyclic.block.clock.TileRedstoneClock;
import com.lothrazar.cyclic.block.collectfluid.TileFluidCollect;
import com.lothrazar.cyclic.block.collectitem.TileItemCollector;
import com.lothrazar.cyclic.block.conveyor.TileConveyor;
import com.lothrazar.cyclic.block.crafter.TileCrafter;
import com.lothrazar.cyclic.block.crate.TileCrate;
import com.lothrazar.cyclic.block.cratemini.TileCrateMini;
import com.lothrazar.cyclic.block.creativeitem.TileItemInfinite;
import com.lothrazar.cyclic.block.crusher.TileCrusher;
import com.lothrazar.cyclic.block.detectmoon.TileMoon;
import com.lothrazar.cyclic.block.detectorentity.TileDetector;
import com.lothrazar.cyclic.block.detectoritem.TileDetectorItem;
import com.lothrazar.cyclic.block.detectweather.TileWeather;
import com.lothrazar.cyclic.block.dice.TileDice;
import com.lothrazar.cyclic.block.disenchant.TileDisenchant;
import com.lothrazar.cyclic.block.dropper.TileDropper;
import com.lothrazar.cyclic.block.enderctrl.TileEnderCtrl;
import com.lothrazar.cyclic.block.enderitemshelf.TileItemShelf;
import com.lothrazar.cyclic.block.endershelf.TileEnderShelf;
import com.lothrazar.cyclic.block.expcollect.TileExpPylon;
import com.lothrazar.cyclic.block.eye.TileEye;
import com.lothrazar.cyclic.block.eyetp.TileEyeTp;
import com.lothrazar.cyclic.block.facade.light.TileLightFacade;
import com.lothrazar.cyclic.block.facade.soundmuff.SoundmuffTileFacade;
import com.lothrazar.cyclic.block.fan.TileFan;
import com.lothrazar.cyclic.block.fanslab.TileFanSlab;
import com.lothrazar.cyclic.block.fishing.TileFisher;
import com.lothrazar.cyclic.block.forester.TileForester;
import com.lothrazar.cyclic.block.generatorfluid.TileGeneratorFluid;
import com.lothrazar.cyclic.block.generatorfood.TileGeneratorFood;
import com.lothrazar.cyclic.block.generatorfuel.TileGeneratorFuel;
import com.lothrazar.cyclic.block.generatoritem.TileGeneratorDrops;
import com.lothrazar.cyclic.block.generatorsolar.TileGeneratorSolar;
import com.lothrazar.cyclic.block.harvester.TileHarvester;
import com.lothrazar.cyclic.block.hopper.TileSimpleHopper;
import com.lothrazar.cyclic.block.hopperfluid.TileFluidHopper;
import com.lothrazar.cyclic.block.hoppergold.TileGoldHopper;
import com.lothrazar.cyclic.block.laser.TileLaser;
import com.lothrazar.cyclic.block.magnet.TileInsertingMagnet;
import com.lothrazar.cyclic.block.melter.TileMelter;
import com.lothrazar.cyclic.block.miner.TileMiner;
import com.lothrazar.cyclic.block.packager.TilePackager;
import com.lothrazar.cyclic.block.peatfarm.TilePeatFarm;
import com.lothrazar.cyclic.block.phantom.MembraneLampTile;
import com.lothrazar.cyclic.block.phantom.SoilTile;
import com.lothrazar.cyclic.block.placer.TilePlacer;
import com.lothrazar.cyclic.block.placerfluid.TilePlacerFluid;
import com.lothrazar.cyclic.block.rotator.TileRotator;
import com.lothrazar.cyclic.block.screen.TileScreentext;
import com.lothrazar.cyclic.block.shapebuilder.TileStructure;
import com.lothrazar.cyclic.block.shapedata.TileShapedata;
import com.lothrazar.cyclic.block.solidifier.TileSolidifier;
import com.lothrazar.cyclic.block.soundplay.TileSoundPlayer;
import com.lothrazar.cyclic.block.soundrecord.TileSoundRecorder;
import com.lothrazar.cyclic.block.spawntriggers.TileAltar;
import com.lothrazar.cyclic.block.spawntriggers.TilePeace;
import com.lothrazar.cyclic.block.spikes.TileDiamondSpikes;
import com.lothrazar.cyclic.block.expfountain.TileExperienceFountain;
import com.lothrazar.cyclic.block.sprinkler.TileSprinkler;
import com.lothrazar.cyclic.block.tank.TileTank;
import com.lothrazar.cyclic.block.tankcask.TileCask;
import com.lothrazar.cyclic.block.terraglass.TileTerraGlass;
import com.lothrazar.cyclic.block.terrasoil.TileTerraPreta;
import com.lothrazar.cyclic.block.tp.TileTeleport;
import com.lothrazar.cyclic.block.trash.TileTrash;
import com.lothrazar.cyclic.block.uncrafter.TileUncraft;
import com.lothrazar.cyclic.block.user.TileUser;
import com.lothrazar.cyclic.block.wireless.energy.TileWirelessEnergy;
import com.lothrazar.cyclic.block.wireless.fluid.TileWirelessFluid;
import com.lothrazar.cyclic.block.wireless.item.TileWirelessItem;
import com.lothrazar.cyclic.block.wireless.redstone.TileWirelessRec;
import com.lothrazar.cyclic.block.wireless.redstone.TileWirelessTransmit;
import com.lothrazar.cyclic.block.workbench.TileWorkbench;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.world.level.block.entity.BlockEntityType;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;

public class TileRegistry {

  public static final DeferredRegister<BlockEntityType<?>> TILES = DeferredRegister.create(BuiltInRegistries.BLOCK_ENTITY_TYPE, ModCyclic.MODID);
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileFluidHopper>> HOPPER_FLUID = TILES.register("hopper_fluid", () -> new BlockEntityType<>(TileFluidHopper::new, BlockRegistry.HOPPER_FLUID.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileSimpleHopper>> HOPPER = TILES.register("hopper", () -> new BlockEntityType<>(TileSimpleHopper::new, BlockRegistry.HOPPER.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileGoldHopper>> HOPPER_GOLD = TILES.register("hopper_gold", () -> new BlockEntityType<>(TileGoldHopper::new, BlockRegistry.HOPPER_GOLD.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileAnvilVoid>> ANVILVOID = TILES.register("anvil_void", () -> new BlockEntityType<>(TileAnvilVoid::new, BlockRegistry.ANVILVOID.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileFanSlab>> FAN_SLAB = TILES.register("fan_slab", () -> new BlockEntityType<>(TileFanSlab::new, BlockRegistry.FAN_SLAB.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileRotator>> ROTATOR = TILES.register("rotator", () -> new BlockEntityType<>(TileRotator::new, BlockRegistry.ROTATOR.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileMoon>> DETECTOR_MOON = TILES.register("detector_moon", () -> new BlockEntityType<>(TileMoon::new, BlockRegistry.DETECTOR_MOON.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileWeather>> DETECTOR_WEATHER = TILES.register("detector_weather", () -> new BlockEntityType<>(TileWeather::new, BlockRegistry.DETECTOR_WEATHER.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileTerraGlass>> GLASS_TERRA = TILES.register("glass_terra", () -> new BlockEntityType<>(TileTerraGlass::new, BlockRegistry.GLASS_TERRA.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileSprinkler>> SPRINKLER = TILES.register("sprinkler", () -> new BlockEntityType<>(TileSprinkler::new, BlockRegistry.SPRINKLER.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileItemShelf>> SHELF = TILES.register("shelf", () -> new BlockEntityType<>(TileItemShelf::new, BlockRegistry.SHELF.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileWirelessEnergy>> WIRELESS_ENERGY = TILES.register("wireless_energy", () -> new BlockEntityType<>(TileWirelessEnergy::new, BlockRegistry.WIRELESS_ENERGY.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileWirelessItem>> WIRELESS_ITEM = TILES.register("wireless_item", () -> new BlockEntityType<>(TileWirelessItem::new, BlockRegistry.WIRELESS_ITEM.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileWirelessFluid>> WIRELESS_FLUID = TILES.register("wireless_fluid", () -> new BlockEntityType<>(TileWirelessFluid::new, BlockRegistry.WIRELESS_FLUID.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileSoundRecorder>> SOUND_RECORDER = TILES.register("sound_recorder", () -> new BlockEntityType<>(TileSoundRecorder::new, BlockRegistry.SOUND_RECORDER.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileSoundPlayer>> SOUND_PLAYER = TILES.register("sound_player", () -> new BlockEntityType<>(TileSoundPlayer::new, BlockRegistry.SOUND_PLAYER.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileGeneratorFuel>> GENERATOR_FUEL = TILES.register("generator_fuel", () -> new BlockEntityType<>(TileGeneratorFuel::new, BlockRegistry.GENERATOR_FUEL.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileGeneratorFood>> GENERATOR_FOOD = TILES.register("generator_food", () -> new BlockEntityType<>(TileGeneratorFood::new, BlockRegistry.GENERATOR_FOOD.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileGeneratorDrops>> GENERATOR_ITEM = TILES.register("generator_item", () -> new BlockEntityType<>(TileGeneratorDrops::new, BlockRegistry.GENERATOR_ITEM.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileGeneratorFluid>> GENERATOR_FLUID = TILES.register("generator_fluid", () -> new BlockEntityType<>(TileGeneratorFluid::new, BlockRegistry.GENERATOR_FLUID.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileGeneratorSolar>> GENERATOR_SOLAR = TILES.register("generator_solar", () -> new BlockEntityType<>(TileGeneratorSolar::new, BlockRegistry.GENERATOR_SOLAR.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TilePackager>> PACKAGER = TILES.register("packager", () -> new BlockEntityType<>(TilePackager::new, BlockRegistry.PACKAGER.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<MembraneLampTile>> LAMP = TILES.register("lamp", () -> new BlockEntityType<>(MembraneLampTile::new, BlockRegistry.LAMP.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<SoilTile>> SOIL = TILES.register("soil", () -> new BlockEntityType<>(SoilTile::new, BlockRegistry.SOIL.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileCrusher>> CRUSHER = TILES.register("crusher", () -> new BlockEntityType<>(TileCrusher::new, BlockRegistry.CRUSHER.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileTeleport>> TELEPORT = TILES.register("teleport", () -> new BlockEntityType<>(TileTeleport::new, BlockRegistry.TELEPORT.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileDiamondSpikes>> SPIKES_DIAMOND = TILES.register("spikes_diamond", () -> new BlockEntityType<>(TileDiamondSpikes::new, BlockRegistry.SPIKES_DIAMOND.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileLightFacade>> LIGHT_CAMO = TILES.register("light_camo", () -> new BlockEntityType<>(TileLightFacade::new, BlockRegistry.LIGHT_CAMO.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<SoundmuffTileFacade>> SOUNDPROOFING_GHOST = TILES.register("soundproofing_ghost", () -> new BlockEntityType<>(SoundmuffTileFacade::new, BlockRegistry.SOUNDPROOFING_GHOST.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileTerraPreta>> TERRA_PRETA = TILES.register("terra_preta", () -> new BlockEntityType<>(TileTerraPreta::new, BlockRegistry.TERRA_PRETA.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileEye>> EYE_REDSTONE = TILES.register("ender_eye_block", () -> new BlockEntityType<>(TileEye::new, BlockRegistry.EYE_REDSTONE.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileEyeTp>> EYE_TELEPORT = TILES.register("ender_pearl_block", () -> new BlockEntityType<>(TileEyeTp::new, BlockRegistry.EYE_TELEPORT.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileAnvilMagma>> ANVIL_MAGMA = TILES.register("anvil_magma", () -> new BlockEntityType<>(TileAnvilMagma::new, BlockRegistry.ANVIL_MAGMA.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TilePotionBeacon>> BEACON = TILES.register("beacon", () -> new BlockEntityType<>(TilePotionBeacon::new, BlockRegistry.BEACON.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileBatteryInfinite>> BATTERY_INFINITE = TILES.register("battery_infinite", () -> new BlockEntityType<>(TileBatteryInfinite::new, BlockRegistry.BATTERY_INFINITE.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileItemInfinite>> ITEM_INFINITE = TILES.register("item_infinite", () -> new BlockEntityType<>(TileItemInfinite::new, BlockRegistry.ITEM_INFINITE.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileDice>> DICE = TILES.register("dice", () -> new BlockEntityType<>(TileDice::new, BlockRegistry.DICE.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileDropper>> DROPPER = TILES.register("dropper", () -> new BlockEntityType<>(TileDropper::new, BlockRegistry.DROPPER.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileForester>> FORESTER = TILES.register("forester", () -> new BlockEntityType<>(TileForester::new, BlockRegistry.FORESTER.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileMiner>> MINER = TILES.register("miner", () -> new BlockEntityType<>(TileMiner::new, BlockRegistry.MINER.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileScreentext>> SCREEN = TILES.register("screen", () -> new BlockEntityType<>(TileScreentext::new, BlockRegistry.SCREEN.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileUncraft>> UNCRAFTER = TILES.register("uncrafter", () -> new BlockEntityType<>(TileUncraft::new, BlockRegistry.UNCRAFTER.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TilePlacerFluid>> PLACER_FLUID = TILES.register("placer_fluid", () -> new BlockEntityType<>(TilePlacerFluid::new, BlockRegistry.PLACER_FLUID.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileCask>> CASK = TILES.register("cask", () -> new BlockEntityType<>(TileCask::new, BlockRegistry.CASK.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileCrate>> CRATE = TILES.register("crate", () -> new BlockEntityType<>(TileCrate::new, BlockRegistry.CRATE.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileCrateMini>> CRATE_MINI = TILES.register("crate_mini", () -> new BlockEntityType<>(TileCrateMini::new, BlockRegistry.CRATE_MINI.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileRedstoneClock>> CLOCK = TILES.register("clock", () -> new BlockEntityType<>(TileRedstoneClock::new, BlockRegistry.CLOCK.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileWirelessRec>> WIRELESS_RECEIVER = TILES.register("wireless_receiver", () -> new BlockEntityType<>(TileWirelessRec::new, BlockRegistry.WIRELESS_RECEIVER.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileWirelessTransmit>> WIRELESS_TRANSMITTER = TILES.register("wireless_transmitter", () -> new BlockEntityType<>(TileWirelessTransmit::new, BlockRegistry.WIRELESS_TRANSMITTER.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileFluidCollect>> COLLECTOR_FLUID = TILES.register("collector_fluid", () -> new BlockEntityType<>(TileFluidCollect::new, BlockRegistry.COLLECTOR_FLUID.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileDisenchant>> DISENCHANTER = TILES.register("disenchanter", () -> new BlockEntityType<>(TileDisenchant::new, BlockRegistry.DISENCHANTER.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileDetectorItem>> DETECTOR_ITEM = TILES.register("detector_item", () -> new BlockEntityType<>(TileDetectorItem::new, BlockRegistry.DETECTOR_ITEM.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileDetector>> DETECTOR_ENTITY = TILES.register("detector_entity", () -> new BlockEntityType<>(TileDetector::new, BlockRegistry.DETECTOR_ENTITY.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileSolidifier>> SOLIDIFIER = TILES.register("solidifier", () -> new BlockEntityType<>(TileSolidifier::new, BlockRegistry.SOLIDIFIER.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileMelter>> MELTER = TILES.register("melter", () -> new BlockEntityType<>(TileMelter::new, BlockRegistry.MELTER.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileTank>> TANK = TILES.register("tank", () -> new BlockEntityType<>(TileTank::new, BlockRegistry.TANK.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileBreaker>> BREAKER = TILES.register("breaker", () -> new BlockEntityType<>(TileBreaker::new, BlockRegistry.BREAKER.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileItemCollector>> COLLECTOR = TILES.register("collector", () -> new BlockEntityType<>(TileItemCollector::new, BlockRegistry.COLLECTOR.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileFan>> FAN = TILES.register("fan", () -> new BlockEntityType<>(TileFan::new, BlockRegistry.FAN.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileExpPylon>> EXPERIENCE_PYLON = TILES.register("experience_pylon", () -> new BlockEntityType<>(TileExpPylon::new, BlockRegistry.EXPERIENCE_PYLON.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileExperienceFountain>> EXPERIENCE_FOUNTAIN = TILES.register("experience_fountain", () -> new BlockEntityType<>(TileExperienceFountain::new, BlockRegistry.EXPERIENCE_FOUNTAIN.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileTrash>> TRASH = TILES.register("trash", () -> new BlockEntityType<>(TileTrash::new, BlockRegistry.TRASH.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileInsertingMagnet>> MAGNET = TILES.register("magnet", () -> new BlockEntityType<>(TileInsertingMagnet::new, BlockRegistry.MAGNET_BLOCK.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TilePeatFarm>> PEAT_FARM = TILES.register("peat_farm", () -> new BlockEntityType<>(TilePeatFarm::new, BlockRegistry.PEAT_FARM.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileBattery>> BATTERY = TILES.register("battery", () -> new BlockEntityType<>(TileBattery::new, BlockRegistry.BATTERY.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileClayBattery>> BATTERY_CLAY = TILES.register("battery_clay", () -> new BlockEntityType<>(TileClayBattery::new, BlockRegistry.BATTERY_CLAY.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileCableEnergy>> ENERGY_PIPE = TILES.register("energy_pipe", () -> new BlockEntityType<>(TileCableEnergy::new, BlockRegistry.ENERGY_PIPE.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileCableItem>> ITEM_PIPE = TILES.register("item_pipe", () -> new BlockEntityType<>(TileCableItem::new, BlockRegistry.ITEM_PIPE.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileCableFluid>> FLUID_PIPE = TILES.register("fluid_pipe", () -> new BlockEntityType<>(TileCableFluid::new, BlockRegistry.FLUID_PIPE.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileCableBundled>> BUNDLED_PIPE = TILES.register("bundled_pipe", () -> new BlockEntityType<>(TileCableBundled::new, BlockRegistry.BUNDLED_PIPE.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileHarvester>> HARVESTER = TILES.register("harvester", () -> new BlockEntityType<>(TileHarvester::new, BlockRegistry.HARVESTER.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileAnvilAuto>> ANVIL = TILES.register("anvil", () -> new BlockEntityType<>(TileAnvilAuto::new, BlockRegistry.ANVIL.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TilePlacer>> PLACER = TILES.register("placer", () -> new BlockEntityType<>(TilePlacer::new, BlockRegistry.PLACER.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileStructure>> STRUCTURE = TILES.register("structure", () -> new BlockEntityType<>(TileStructure::new, BlockRegistry.STRUCTURE.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileFisher>> FISHER = TILES.register("fisher", () -> new BlockEntityType<>(TileFisher::new, BlockRegistry.FISHER.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileUser>> USER = TILES.register("user", () -> new BlockEntityType<>(TileUser::new, BlockRegistry.USER.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileCrafter>> CRAFTER = TILES.register("crafter", () -> new BlockEntityType<>(TileCrafter::new, BlockRegistry.CRAFTER.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileShapedata>> COMPUTER_SHAPE = TILES.register("computer_shape", () -> new BlockEntityType<>(TileShapedata::new, BlockRegistry.COMPUTER_SHAPE.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<UnbreakablePoweredTile>> UNBREAKABLE_REACTIVE = TILES.register("unbreakable_reactive", () -> new BlockEntityType<>(UnbreakablePoweredTile::new, BlockRegistry.UNBREAKABLE_REACTIVE.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileLaser>> LASER = TILES.register("laser", () -> new BlockEntityType<>(TileLaser::new, BlockRegistry.LASER.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileConveyor>> CONVEYOR = TILES.register("conveyor", () -> new BlockEntityType<>(TileConveyor::new, BlockRegistry.CONVEYOR.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileEnderShelf>> ENDER_SHELF = TILES.register("ender_shelf", () -> new BlockEntityType<>(TileEnderShelf::new, BlockRegistry.ENDER_SHELF.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileEnderCtrl>> ENDER_CONTROLLER = TILES.register("ender_controller", () -> new BlockEntityType<>(TileEnderCtrl::new, BlockRegistry.ENDER_CONTROLLER.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileWorkbench>> WORKBENCH = TILES.register("workbench", () -> new BlockEntityType<>(TileWorkbench::new, BlockRegistry.WORKBENCH.get()));
  //
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileAntiBeacon>> BEACON_SPONGE = TILES.register("beacon_sponge", () -> new BlockEntityType<>(TileAntiBeacon::new, BlockRegistry.BEACON_SPONGE.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileBeaconRedstone>> BEACON_REDSTONE = TILES.register("beacon_redstone", () -> new BlockEntityType<>(TileBeaconRedstone::new, BlockRegistry.BEACON_REDSTONE.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TilePeace>> CANDLE_PEACE = TILES.register("candle_peace", () -> new BlockEntityType<>(TilePeace::new, BlockRegistry.CANDLE_PEACE.get()));
  public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<TileAltar>> ALTAR_SOLICITING = TILES.register("altar_soliciting", () -> new BlockEntityType<>(TileAltar::new, BlockRegistry.ALTAR_SOLICITING.get()));
}
